const { GoogleGenAI } = require('@google/genai')
const {z} = require('zod');
const {zodToJsonSchema} = require('zod-to-json-schema');

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
    matchScore: z.number().describe('A score between 0 and 100 indicating how well the candidate matches the job describe'),
    technicalQuestions: z.array(z.object({
        question: z.string().describe('The technical question that can be asked in the interview'),
        intension: z.string().describe('The intension of interviewer behind asking this question'),
        answer: z.string().describe('How to answer this question, what points to cover, what approach to take, what to avoid, etc.'),
    })).describe('Technical questions that can be asked in the interview, along with their intensions and how to answer them'),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe('The behavioral question that can be asked in the interview'),
        intension: z.string().describe('The intension of interviewer behind asking this question'),
        answer: z.string().describe('How to answer this question, what points to cover, what approach to take, what to avoid, etc.'),
    })).describe('Behavioral questions that can be asked in the interview, along with their intensions and how to answer them'),
    skillGaps: z.array(z.object({
        skill: z.string().describe('The skill which the candidate is lacking'),
        severity: z.enum(['low', 'medium', 'high']).describe('The severity level of the skill gap'),
    })).describe('A list of skills gap and their severity levels'),
    preparationPlans: z.array(z.object({
        day: z.number().describe('The day number in the preparation plan, starting from 1'),
        focus: z.string().describe('The main focus of the day in the preparation plan'),
        tasks: z.array(z.string()).describe('A list of tasks to be completed on that day'),
    })).describe('A day-wise preparation plan for the candidate to follow, with focus areas and tasks for each day'),
}).describe('The structure of the interview report generated by the AI');

async function generateInterviewReport(jobDescription, resumeText, selfDescription) {

    const prompt = `Generate an interview report for a candidate based on the following information:
                    Job Description: ${jobDescription}
                    Resume: ${resume}
                    Self Description: ${selfDescription}`

    const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents : prompt,
        config :{
            responseMimeType: 'application/json',
            responseSchema: zodToJsonSchema(interviewReportSchema)
        }
})

}

console.log(JSON.parse(response.text));

module.exports = generateInterviewReport;
